# ueransim-gnb-values.yaml

# gNB + UE simulator values
name: ueransim-gnb
amf:
  hostname: open5gs-amf-ngap
  ip: ""          # let hostname take precedence

interfaces:
  n2:
    dev: eth0
  n3:
    dev: eth0
  radio:
    dev: eth0

mcc: '999'
mnc: '70'
sst: 1
sd: "0x111111"
tac: '0001'

ues:
  enabled: true
  count: 2
  initialMSISDN: '0000000001'
  key: 465B5CE8B199B49FAA5F0A2EE238A6BC
  op: E8ED289DEBA952E4283B54E88E6183CA
  opType: OPC
  apnList:
    - type: 'IPv4'
      apn: 'internet'
      slice:
        sst: 1
        sd: "0x111111"
      emergency: false

# Turn off 4G-only NFs here
hss:
  enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

# Echo 5GC core helpers/config for completeness
smf:
  config:
    pcrf:
      enabled: false

amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

nssf:
  config:
    nsiList:
      - uri: ""
        sst: 1
        sd: "0x111111"
